### 1. Importing libraries to fetch data

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('data/train.csv')
df.head(20)

,id,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents,accident_risk
0,0,urban,2,0.06,35,daylight,rainy,False,True,afternoon,False,True,1,0.13
1,1,urban,4,0.99,35,daylight,clear,True,False,evening,True,True,0,0.35
2,2,rural,4,0.63,70,dim,clear,False,True,morning,True,False,2,0.30
3,3,highway,4,0.07,35,dim,rainy,True,True,morning,False,False,1,0.21
4,4,rural,1,0.58,60,daylight,foggy,False,False,evening,True,False,1,0.56
5,5,highway,3,0.54,70,night,foggy,True,False,morning,False,True,0,0.61
6,6,highway,1,0.04,45,night,foggy,False,True,morning,True,False,2,0.20
7,7,highway,2,0.33,45,daylight,clear,False,True,evening,False,True,0,0.16
8,8,rural,3,0.63,25,dim,clear,True,False,evening,True,True,2,0.18
9,9,urban,4,0.38,45,dim,clear,True,True,afternoon,True,True,2,0.15
10,10,highway,1,0.45,45,dim,clear,False,False,afternoon,True,False,2,0.06
11,11,highway,4,0.26,60,daylight,foggy,True,False,evening,False,False,0,0.32
12,12,urban,4,0.84,25,dim,rainy,True,True,morning,False,True,2,0.37
13,13,rural,4,0.14,60,daylight,foggy,True,True,evening,True,True,1,0.28
14,14,highway,3,0.08,45,dim,foggy,False,False,evening,True,False,1,0.17
15,15,urban,1,0.52,60,daylight,clear,False,True,afternoon,True,False,1,0.39
16,16,highway,3,0.35,35,daylight,foggy,False,False,evening,True,True,1,0.23
17,17,rural,4,0.68,35,night,clear,False,True,morning,True,False,3,0.51
18,18,rural,3,0.72,60,night,foggy,True,True,afternoon,True,True,0,0.63
19,19,highway,2,0.86,70,night,clear,False,False,evening,False,False,3,0.79

### 2. Fetching more info on dataset

In [15]:
print("No. of rows & cols. are :",df.shape)

No. of rows & cols. are : (517754, 14)

In [18]:
print("Summary of numerical cols. of dataset\n",df.describe())

Summary of numerical cols. of dataset
                   id      num_lanes      curvature    speed_limit  \
count  517754.000000  517754.000000  517754.000000  517754.000000
mean   258876.500000       2.491511       0.488719      46.112575
std    149462.849974       1.120434       0.272563      15.788521
min         0.000000       1.000000       0.000000      25.000000
25%    129438.250000       1.000000       0.260000      35.000000
50%    258876.500000       2.000000       0.510000      45.000000
75%    388314.750000       3.000000       0.710000      60.000000
max    517753.000000       4.000000       1.000000      70.000000

       num_reported_accidents  accident_risk
count           517754.000000  517754.000000
mean                 1.187970       0.352377
std                  0.895961       0.166417
min                  0.000000       0.000000
25%                  1.000000       0.230000
50%                  1.000000       0.340000
75%                  2.000000       0.460000
max                  7.000000       1.000000

### 3. Checking for missing & duplicate values in dataset

In [5]:
df.isnull().sum()

id                        0
road_type                 0
num_lanes                 0
curvature                 0
speed_limit               0
lighting                  0
weather                   0
road_signs_present        0
public_road               0
time_of_day               0
holiday                   0
school_season             0
num_reported_accidents    0
accident_risk             0
dtype: int64

In [19]:
print("No. of duplicate rows in the dataset: ",df.duplicated().sum())

No. of duplicate rows in the dataset:  0

#### 4. Let's learn more about the types of datatypes of columns

In [12]:
categorical_cols = df.select_dtypes(include=['object','category','boolean'])
categorical_cols

,road_type,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season
0,urban,daylight,rainy,False,True,afternoon,False,True
1,urban,daylight,clear,True,False,evening,True,True
2,rural,dim,clear,False,True,morning,True,False
3,highway,dim,rainy,True,True,morning,False,False
4,rural,daylight,foggy,False,False,evening,True,False
...,...,...,...,...,...,...,...,...
517749,highway,daylight,foggy,True,True,afternoon,False,False
517750,rural,daylight,rainy,True,True,morning,False,False
517751,urban,daylight,foggy,False,False,afternoon,False,True
517752,highway,night,clear,True,False,afternoon,True,True
517753,highway,dim,rainy,False,True,afternoon,True,True

In [14]:
numerical_cols = df.select_dtypes(include =['int','float'])
numerical_cols

,id,num_lanes,curvature,speed_limit,num_reported_accidents,accident_risk
0,0,2,0.06,35,1,0.13
1,1,4,0.99,35,0,0.35
2,2,4,0.63,70,2,0.30
3,3,4,0.07,35,1,0.21
4,4,1,0.58,60,1,0.56
...,...,...,...,...,...,...
517749,517749,4,0.10,70,2,0.32
517750,517750,4,0.47,35,1,0.26
517751,517751,4,0.62,25,0,0.19
517752,517752,3,0.63,25,3,0.51
517753,517753,2,0.31,45,2,0.22

# Since there are no duplicates, null values & incorrect datatypes in this dataset, I would move on to perform EDA in the next notebook.